# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :grub => {
        :box_name => "centos/7",
		:net => [],
		:cpus => 1,
		:memory => 1024,
  },
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
            if boxconfig.key?(:net)
				boxconfig[:net].each do |ipconf|
					box.vm.network "private_network", ipconf
				end
			end
			box.vm.provider :virtualbox do |vb|
                vb.memory = boxconfig[:memory]
				vb.cpus = boxconfig[:cpus]
            end
        end
    end
  end
