# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
	:lab2 => {
		:box_name => "centos/stream8",
		:cpus => 4,
		:memory => 4096,
		:disks => {
			:sata1 => {
				:dfile => './disk1.vdi',
				:size => 40960,
				:port => 1
			}
		}
	},
}

Vagrant.configure("2") do |config|
	MACHINES.each do |boxname, boxconfig|
		config.vm.define boxname do |box|
			box.vm.box = boxconfig[:box_name]
			box.vm.host_name = boxname.to_s
			if boxconfig.key?(:forwarded_port)
				boxconfig[:forwarded_port].each do |port|
					box.vm.network "forwarded_port", port
				end
			end
			box.vm.provider :virtualbox do |vb|
				vb.memory = boxconfig[:memory]
				vb.cpus = boxconfig[:cpus]
				needsController = false
				boxconfig[:disks].each do |dname, dconf|
					unless File.exist?(dconf[:dfile])
						vb.customize ['createhd', '--filename', dconf[:dfile], '--size', dconf[:size]]
						needsController =  true
					end
				end
				if needsController == true
					vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
					boxconfig[:disks].each do |dname, dconf|
						vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
					end
				end
			end
			box.vm.provision "shell", inline: <<-SHELL
				mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				yum install -y mdadm smartmontools hdparm gdisk
				# Script for RAID 1
				#Создаем таблицу разделов на втором диске, такую же как и на первом
				#sfdisk -d /dev/sda | sfdisk /dev/sdb
			SHELL
		end
	end
end