# -*- mode: ruby -*-
# vim: set ft=ruby :
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :grub => {
        :box_name => "centos/7",
		:net => [],
		:cpus => 1,
		:memory => 1024,
  },
}

Vagrant.configure("2") do |config|
    config.vm.box_version = "2004.01" 
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
            #box.vm.network "private_network", ip: boxconfig[:ip_addr]
			box.vm.provider :virtualbox do |vb|
				vb.memory = boxconfig[:memory]
				vb.cpus = boxconfig[:cpus]
            end
        end
    end
  end
